apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-pet
    spec:
     containers:
        - name: petclinic
          image: sandeepds2002/petclinic
          ports:
            - 8081 : 8080
