- hosts: web
  sudo: yes 
  
  tasks: 
  - name: Remove old docker image
    docker:
      image: sandeepds2002/petclinic
      name: petclinic
      expose: 8080
      ports:
      - 8081:8080
      state:  killed
      
  - name: Docker Pull and Run
    docker:
      name: petclinic
      image:  sandeepds2002/petclinic
      pull: always
      expose: 8080
      ports:
      - 8081:8080
      state:  restarted
