- hosts: client
  become: yes
  
  tasks:
  
   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg

   - name: Add Docker APT repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

   - name : install docker
     apt:
       name: docker-ce
       state: present
          
   - name: login to Docker hub
     command: docker login --username=sandeepds2002 --email=sandeepds2002@gmail.com
     
   - name: Pull Docker image
     command: docker image pull sandeepds2002/petclinic
    
   - name : Run docker image
     command: docker-run sandeepds2002/petclinic
