- hosts: client
  become: yes
  
  tasks:
   - name: install pip
     apt:
       name: python-pip
       state: present

   - name: Install prerequisites
     apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      
  tasks: 
  - name: Remove old docker image
    docker_container:
      image: sandeepds2002/petclinic
      name: petclinic
      expose: 8080
      ports:
      - 8081:8080
      state:  absent
      
  - name: Docker Pull and Run
    docker_container:
      name: petclinic
      image:  sandeepds2002/petclinic
      pull: always
      expose: 8080
      ports:
      - 8081:8080
      state:  started
